Vagrant.configure("2") do |config|
  config.vm.box = "raring64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.hostname = 'blog-full.charlieknudsen.com'
  
  config.package.name = "blog-full.box"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.network :private_network, ip: "192.168.70.99"

  chef_dir = File.expand_path("../../")
  config.vm.synced_folder chef_dir, "/opt/chef-solo/website"
  config.vm.provision :shell, :path => "startup.sh"
end
