---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: precise64
  driver_config:
    require_chef_omnibus: true
    box: precise64
    box_url: http://files.vagrantup.com/precise64.box

suites:
- name: blog-full
  run_list:
    - recipe[blog::default]
