---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    require_chef_omnibus: true
    memory: 1700

suites:
- name: blog-full
  run_list:
    - role[etcd]
    - role[nginx]
    - role[database]
    - role[blog-application]
  attributes: {blog: { encrypted: false, create_users: false }, nginx: { ssl: false } }
