#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# The apt 2.3.0 cookbook is giving me errors so just moving back to 2.2.0 for now
cookbook "apt", "2.3.4"
cookbook "etcd", "1.3.5"
cookbook "postgresql", "3.3.4"

cookbook "golang"

cookbook "database", "1.6.0"

cookbook "user",
	:git => "https://github.com/fnichol/chef-user.git"

cookbook "blog",
  :path => "site-cookbooks/blog"
