source "https://rubygems.org"

gem "librarian-chef", ">= 0.0.2"
gem "foodcritic", ">=3.0.3"
gem 'test-kitchen', ">=0.12.0", :group => :integration
gem 'kitchen-vagrant', ">=1.0.0", :group => :integration
